version: "3.7"

services:
    database_devrun:
      image: postgres
      container_name: database_devrun
      restart: always
      ports: 
        - 5432:5432
      environment: 
        - POSTGRES_USER=docker_rundev
        - POSTGRES_PASSWORD=rundev
        - POSTGRES_DB=devrun
      volumes: 
        - pgdata:/data/postgres       
    app:
      build: .
      container_name: devrun_api
      restart: always
      ports: 
        - 3333:3333
      volumes: 
        - .:/usr/app

      links: 
        - database_devrun
      depends_on: 
        - database_devrun              
volumes: 
    pgdata:
      driver: local         